apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.service-settings - This section contains the YAML of the service's service-setting
    # see https://www.spinnaker.io/reference/halyard/custom/#tweakable-service-settings for available settings
    service-settings:
      clouddriver: {}

      deck: {}

      echo:
        env:
          JAVA_OPTS: "-Xms256m -Xmx512m"

      fiat: {}

      front50: {}

      gate: {}

      igor: {}

      kayenta: {}

      orca: {}

      rosco: {}
