apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: spinnakerservices.spinnaker.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.version
    description: Version
    name: version
    type: string
  - JSONPath: .status.lastConfigurationTime
    description: Last Configured
    name: lastConfigured
    type: date
  - JSONPath: .status.status
    description: Status
    name: status
    type: string
  - JSONPath: .status.serviceCount
    description: Services
    name: services
    type: number
  - JSONPath: .status.uiUrl
    description: URL
    name: url
    type: string
  - JSONPath: .status.apiUrl
    description: API URL
    name: apiUrl
    priority: 1
    type: string
  group: spinnaker.io
  names:
    kind: SpinnakerService
    listKind: SpinnakerServiceList
    plural: spinnakerservices
    shortNames:
    - spinsvc
    singular: spinnakerservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SpinnakerService is the Schema for the spinnakerservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SpinnakerServiceSpec defines the desired state of SpinnakerService
          properties:
            accounts:
              properties:
                dynamic:
                  description: Enable accounts to be added dynamically
                  type: boolean
                enabled:
                  description: Enable the injection of SpinnakerAccount
                  type: boolean
              type: object
            expose:
              description: ExposeConfig represents the configuration for exposing
                Spinnaker
              properties:
                service:
                  description: ExposeConfigService represents the configuration for
                    exposing Spinnaker using k8s services
                  properties:
                    annotations:
                      additionalProperties:
                        type: string
                      type: object
                    overrides:
                      additionalProperties:
                        description: ExposeConfigServiceOverrides represents expose
                          configurations of type service, overriden by specific services
                        properties:
                          annotations:
                            additionalProperties:
                              type: string
                            type: object
                          publicPort:
                            format: int32
                            type: integer
                          type:
                            type: string
                        type: object
                      type: object
                    publicPort:
                      format: int32
                      type: integer
                    type:
                      type: string
                  type: object
                type:
                  type: string
              type: object
            spinnakerConfig:
              properties:
                config:
                  description: Main deployment configuration to be passed to Halyard
                files:
                  additionalProperties:
                    type: string
                  description: Supporting files for the Spinnaker config
                  type: object
                profiles:
                  additionalProperties: {}
                  description: Service profiles will be parsed as YAML
                  type: object
                service-settings:
                  description: Parsed service settings - comments are stripped
              type: object
          required:
          - spinnakerConfig
          type: object
        status:
          description: SpinnakerServiceStatus defines the observed state of SpinnakerService
          properties:
            accountCount:
              description: Number of accounts
              type: integer
            apiUrl:
              description: Exposed Gate URL
              type: string
            lastConfigHash:
              description: Last deployed hash
              type: string
            lastConfigurationTime:
              description: Last time the configuration was updated
              format: date-time
              type: string
            serviceCount:
              description: Number of services in Spinnaker
              type: integer
            services:
              description: Services deployment information
              items:
                description: SpinnakerDeploymentStatus represents the deployment status
                  of a single service
                properties:
                  image:
                    description: Image deployed
                    type: string
                  name:
                    description: Name of the service deployed
                    type: string
                  readyReplicas:
                    description: Total number of ready pods targeted by this deployment.
                    format: int32
                    type: integer
                  replicas:
                    description: Total number of non-terminated pods targeted by this
                      deployment (their labels match the selector).
                    format: int32
                    type: integer
                required:
                - name
                type: object
              type: array
            status:
              description: Overall Spinnaker status
              type: string
            uiUrl:
              description: Exposed Deck URL
              type: string
            version:
              description: Current deployed version of Spinnaker
              type: string
          type: object
        validation:
          description: SpinnakerValidation defines validation settings for the deployment
          properties:
            ci:
              items:
                description: ValidationSettingList is a map of ValidationSettings
                  and a top level validation setting
                properties:
                  items:
                    additionalProperties:
                      description: ValidationSetting is the definition of the validation
                        for a given setting
                      properties:
                        enabled:
                          type: boolean
                        failOnError:
                          type: boolean
                        frequencySeconds:
                          format: int64
                          type: integer
                      required:
                      - enabled
                      - failOnError
                      - frequencySeconds
                      type: object
                    type: object
                  validationSetting:
                    description: ValidationSetting is the definition of the validation
                      for a given setting
                    properties:
                      enabled:
                        type: boolean
                      failOnError:
                        type: boolean
                      frequencySeconds:
                        format: int64
                        type: integer
                    required:
                    - enabled
                    - failOnError
                    - frequencySeconds
                    type: object
                required:
                - items
                type: object
              type: array
            failFast:
              type: boolean
            metricStores:
              description: ValidationSetting is the definition of the validation for
                a given setting
              properties:
                enabled:
                  type: boolean
                failOnError:
                  type: boolean
                frequencySeconds:
                  format: int64
                  type: integer
              required:
              - enabled
              - failOnError
              - frequencySeconds
              type: object
            notifications:
              description: ValidationSetting is the definition of the validation for
                a given setting
              properties:
                enabled:
                  type: boolean
                failOnError:
                  type: boolean
                frequencySeconds:
                  format: int64
                  type: integer
              required:
              - enabled
              - failOnError
              - frequencySeconds
              type: object
            persistentStorage:
              description: ValidationSetting is the definition of the validation for
                a given setting
              properties:
                enabled:
                  type: boolean
                failOnError:
                  type: boolean
                frequencySeconds:
                  format: int64
                  type: integer
              required:
              - enabled
              - failOnError
              - frequencySeconds
              type: object
            providers:
              items:
                description: ValidationSettingList is a map of ValidationSettings
                  and a top level validation setting
                properties:
                  items:
                    additionalProperties:
                      description: ValidationSetting is the definition of the validation
                        for a given setting
                      properties:
                        enabled:
                          type: boolean
                        failOnError:
                          type: boolean
                        frequencySeconds:
                          format: int64
                          type: integer
                      required:
                      - enabled
                      - failOnError
                      - frequencySeconds
                      type: object
                    type: object
                  validationSetting:
                    description: ValidationSetting is the definition of the validation
                      for a given setting
                    properties:
                      enabled:
                        type: boolean
                      failOnError:
                        type: boolean
                      frequencySeconds:
                        format: int64
                        type: integer
                    required:
                    - enabled
                    - failOnError
                    - frequencySeconds
                    type: object
                required:
                - items
                type: object
              type: array
            validationSetting:
              description: ValidationSetting is the definition of the validation for
                a given setting
              properties:
                enabled:
                  type: boolean
                failOnError:
                  type: boolean
                frequencySeconds:
                  format: int64
                  type: integer
              required:
              - enabled
              - failOnError
              - frequencySeconds
              type: object
          required:
          - ci
          - failFast
          - metricStores
          - notifications
          - persistentStorage
          - providers
          - validationSetting
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
