apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      version: 1.15.1   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: mybucket
          rootFolder: front50

    # spec.spinnakerConfig.profiles - This section contains the YAML of each service's profile
    profiles:
      deck:
        # settings-local.js - contents of ~/.hal/default/profiles/settings-local.js
        # Use the | YAML symbol to indicate a block-style multiline string
        settings-local.js: |
          window.spinnakerSettings.feature.kustomizeEnabled = true;
          window.spinnakerSettings.feature.artifactsRewrite = true;

      clouddriver: # is the contents of ~/.hal/default/profiles/clouddriver.yml
        serviceLimits:
          defaults:
            rateLimit: 10.0   # default max req/second

      echo: {}    # is the contents of ~/.hal/default/profiles/echo.yml

      fiat: {}    # is the contents of ~/.hal/default/profiles/fiat.yml

      front50: {} # is the contents of ~/.hal/default/profiles/front50.yml

      gate: {}    # is the contents of ~/.hal/default/profiles/gate.yml

      igor: {}    # is the contents of ~/.hal/default/profiles/igor.yml

      kayenta: {} # is the contents of ~/.hal/default/profiles/kayenta.yml

      orca: {}    # is the contents of ~/.hal/default/profiles/orca.yml

      rosco: {}   # is the contents of ~/.hal/default/profiles/rosco.yml


    # spec.spinnakerConfig.service-settings - This section contains the YAML of the service's service-setting
    # see https://www.spinnaker.io/reference/halyard/custom/#tweakable-service-settings for available settings
    service-settings:
      clouddriver: {}

      deck: {}

      echo:
        env:
          JAVA_OPTS: "-Xms256m -Xmx512m"

      fiat: {}

      front50: {}

      gate: {}

      igor: {}

      kayenta: {}

      orca: {}

      rosco: {}


    # spec.spinnakerConfig.files - This section allows you to include any other raw string files not handle above.
    # The KEY is the filepath and filename of where it should be placed
    #   - Files here will be placed into ~/.hal/default/ on halyard
    #   - __ is used in place of / for the path separator
    # The VALUE is the contents of the file.
    #   - Use the | YAML symbol to indicate a block-style multiline string
    #   - We currently only support string files
    #   - NOTE: Kubernetes has a manifest size limitation of 1MB
    files:
      # ~/.hal/default/profiles/rosco/packer/example-packer-config.json
      profiles__rosco__packer__example-packer-config.json: |
        {"packerSetting": "someValue"}

      # ~/.hal/default/profiles/rosco/packer/my_custom_script.sh
      profiles__rosco__packer__my_custom_script.sh: |
        #!/bin/bash -e
        echo "hello world!"


  # spec.expose - This section defines how Spinnaker should be publicly exposed
  expose:
    type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
    service:
      type: LoadBalancer
